version: "3"

services:
  weather_polychrom_dev_ssr:
    image: node:16.3.0-alpine
    container_name: weather_polychrom_dev_ssr
    ports:
      - 4000:4000
    volumes:
      #copy complete /dist because express requests browser view
      - ./dist/weather.polychrom.dev:/dist/weather.polychrom.dev
    command: node /dist/weather.polychrom.dev/server/main.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather_polychrom_dev.entrypoints=websecure"
      - "traefik.http.routers.weather_polychrom_dev.rule=Host(`weather.polychrom.dev`)"
      - "traefik.http.routers.weather_polychrom_dev.tls.certresolver=myresolver"
      - "traefik.port=8016"

    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
