version: "3"

services:
  weather_polychrom_dev_ssr:
    build: .
    container_name: weather_polychrom_dev_ssr
    ports:
      - 4000:4000
    volumes:
      # /dist/server/
      # /dist/browser/
      - ./dist/weather.polychrom.dev:/dist/weather.polychrom.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather_polychrom_dev.entrypoints=websecure"
      - "traefik.http.routers.weather_polychrom_dev.rule=Host(`weather.polychrom.dev`)"
      - "traefik.http.routers.weather_polychrom_dev.tls.certresolver=myresolver"
      - "traefik.port=8016"

    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
